/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialmediaRouteImport } from './routes/socialmedia'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WebdevRouteImport } from './routes/webdev'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialmediaRoute = SocialmediaRouteImport.update({
  id: '/socialmedia',
  path: '/socialmedia',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WebdevRoute = WebdevRouteImport.update({
  id: '/webdev',
  path: '/webdev',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/socialmedia': typeof SocialmediaRoute
  '/team': typeof TeamRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/socialmedia': typeof SocialmediaRoute
  '/team': typeof TeamRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/socialmedia': typeof SocialmediaRoute
  '/team': typeof TeamRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/socialmedia' | '/team' | '/webdev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/socialmedia' | '/team' | '/webdev'
  id: '__root__' | '/' | '/socialmedia' | '/team' | '/webdev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocialmediaRoute: typeof SocialmediaRoute
  TeamRoute: typeof TeamRoute
  WebdevRoute: typeof WebdevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socialmedia': {
      id: '/socialmedia'
      path: '/socialmedia'
      fullPath: '/socialmedia'
      preLoaderRoute: typeof SocialmediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdev': {
      id: '/webdev'
      path: '/webdev'
      fullPath: '/webdev'
      preLoaderRoute: typeof WebdevRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocialmediaRoute: SocialmediaRoute,
  TeamRoute: TeamRoute,
  WebdevRoute: WebdevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
